#!/bin/bash

# Function to check if larawsl is already installed
check_if_larawsl_installed() {
    if command -v larawsl &>/dev/null; then
        echo "larawsl is already installed."
        exit 0
    fi
}

# Function to perform the larawsl installation
install_larawsl() {
    check_if_larawsl_installed
    echo "Downloading and installing larawsl..."
    curl -sSfL https://raw.githubusercontent.com/realanmup/larawsl/main/larawsl -o larawsl.sh
    chmod +x larawsl
    sudo mv larawsl /usr/local/bin/larawsl
    echo "larawsl is now installed. You can start using it by running 'larawsl' in the terminal."
}

install_larawsl
